menu1: menu1.c
	gcc -o $@ $@.c
menu2: menu2.c
	gcc -o $@ $@.c
menu3: menu3.c
	gcc -o $@ $@.c
password: password.c
	gcc -o $@ $@.c
menu4: menu4.c
	gcc -o $@ $@.c
sizeterm: sizeterm.c
	gcc -o $@ $@.c -lncurses
