simple_write: simple_write.c
	gcc -o $@ $@.c
simple_read: simple_read.c
	gcc -o $@ $@.c
copy_system: copy_system.c
	gcc -o $@ $@.c
copy_block: copy_block.c
	gcc -o $@ $@.c
mmap: mmap.c
	gcc -o $@ $@.c
printdir: printdir.c
	gcc -o $@ $@.c
