detach: detach.cpp
	g++ -o $@ $@.cpp -std=c++11
join: join.cpp
	g++ -o $@ $@.cpp -std=c++11
joinable: joinable.cpp
	g++ -o $@ $@.cpp -std=c++11
get_id: get_id.cpp
	g++ -o $@ $@.cpp -std=c++11
hardware_concurrency: hardware_concurrency.cpp
	g++ -o $@ $@.cpp -std=c++11
swap: swap.cpp
	g++ -o $@ $@.cpp -std=c++11
sleep_for: sleep_for.cpp
	g++ -o $@ $@.cpp -std=c++11
yield: yield.cpp
	g++ -o $@ $@.cpp -std=c++11
this_thread_get_id: this_thread_get_id.cpp
	g++ -o $@ $@.cpp -std=c++11
