args: args.c
	gcc -o $@ $@.c
argopt: argopt.c
	gcc -o $@ $@.c
longopt: longopt.c
	gcc -o $@ $@.c
environ: environ.c
	gcc -o $@ $@.c
showenv: showenv.c
	gcc -o $@ $@.c
envtime: envtime.c
	gcc -o $@ $@.c
gmtime: gmtime.c
	gcc -o $@ $@.c
localtime: localtime.c
	gcc -o $@ $@.c
ctime: ctime.c
	gcc -o $@ $@.c
strftime: strftime.c
	gcc -o $@ $@.c
tmpnam: tmpnam.c
	gcc -o $@ $@.c
mktemp: mktemp.c
	gcc -o $@ $@.c
user: user.c
	gcc -o $@ $@.c
passwd: passwd.c
	gcc -o $@ $@.c
hostget: hostget.c
	gcc -o $@ $@.c
