bitset: bitset.cpp
	g++ -o bitset bitset.cpp -std=c++11

random: random.cpp
	g++ -o random random.cpp -std=c++11

uniform_real_distribution: uniform_real_distribution.cpp
	g++ -o $@ $@.cpp -std=c++11

normal_distribution: normal_distribution.cpp
	g++ -o $@ $@.cpp -std=c++11

bernoulli_distribution: bernoulli_distribution.cpp
	g++ -o $@ $@.cpp -std=c++11

binomial_distribution: binomial_distribution.cpp
	g++ -o $@ $@.cpp -std=c++11

seek: seek.cpp
	g++ -o $@ $@.cpp -std=c++11

tuple: tuple.cpp
	g++ -o $@ $@.cpp -std=c++11
