auto: auto.cpp
	g++ -o $@ $@.cpp -std=c++11
char_literal: char_literal.cpp
	g++ -o $@ $@.cpp
const: const.cpp
	g++ -o $@ $@.cpp
const2: const2.cpp
	g++ -o $@ $@.cpp
constexpr: constexpr.cpp
	g++ -o $@ $@.cpp -std=c++11
decltype: decltype.cpp
	g++ -o $@ $@.cpp -std=c++11
list_initialize: list_initialize.cpp
	g++ -o $@ $@.cpp -std=c++11
pointer: pointer.cpp
	g++ -o $@ $@.cpp
reference: reference.cpp
	g++ -o $@ $@.cpp
string_literal: string_literal.cpp
	g++ -o $@ $@.cpp
typealias: typealias.cpp
	g++ -o $@ $@.cpp -std=c++11
unsigned: unsigned.cpp
	g++ -o $@ $@.cpp
