mutex: mutex.cpp
	g++ -o $@ $@.cpp -std=c++11
lock: lock.cpp
	g++ -o $@ $@.cpp -std=c++11
try_lock: try_lock.cpp
	g++ -o $@ $@.cpp -std=c++11
unlock: unlock.cpp
	g++ -o $@ $@.cpp -std=c++11
std_lock: std_lock.cpp
	g++ -o $@ $@.cpp -std=c++11
lock_guard: lock_guard.cpp
	g++ -o $@ $@.cpp -std=c++11
recursive_mutex: recursive_mutex.cpp
	g++ -o $@ $@.cpp -std=c++11
try_lock_for: try_lock_for.cpp
	g++ -o $@ $@.cpp -std=c++11
timed_mutex: timed_mutex.cpp
	g++ -o $@ $@.cpp -std=c++14
