#!/bin/sh


# The dialog command uses text mode graphics and color.
# To get the output of any type of box that allows textual input, or selections,
# you have to capture the standard error stream, usually by directing it to a
# temporary file, which you can then process afterward. To get the result of
# yes/no type questions, just look at the exit code, which, like all
# well-behaved programs, returns 0 for success(i.e., a "yes" selection) or 1 for
# failure.
#
#  Principal types of dialogs you can create and its parameters:
# ******************************************************************************
# --checklist   text height width list-height [tag text status]...
# ******************************************************************************
# --infobox     text height width
# ******************************************************************************
# --inputbox    text height width [initial string]
# ******************************************************************************
# --menu        text height width menu-height [tag item]...
# ******************************************************************************
# --msgbox      text height width
# ******************************************************************************
# --radiolist   text height width list-height [tag text status]...
# ******************************************************************************
# --textbox     filename height width
# ******************************************************************************
# --yesno       text height width
# ******************************************************************************


# Ask some questions and collect the answer
dialog --title "Questionnaire" --msgbox "Welcome to my simple survey" 9 18


# Ask the user if he wants to proceed, using a simple yes/no dialog box.
dialog --title "Confirm" --yesno "Are you willing to take part?" 9 18
if [ $? != 0 ]; then
    dialog --infobx "Thank you anyway" 5 20
    sleep 2
    dialog --clear
    exit 0
fi


# Ask the user his name, using an input box. Redirect the standard error stream,
# 2, into a temporary file, _1.txt
dialog --title "Questionnaire" --inputbox "Please enter your name" 9 30 2>_1.txt
Q_NAME=$(cat _1.txt)


# menu item with four different options
dialog --menu "$Q_NAME, what music do you like best?" 15 30 4 \
    1 "Classical"   2 "Jazz"    3 "Country"     4 "Other" 2>_1.txt
Q_MUSIC=$(cat _1.txt)


# test the result
if [ "$Q_MUSIC" = "1" ]; then
    dialog --title "Likes Classical" --msgbox "Good choice!" 12 25
else
    dialog --title "Doesn't like Classical" --msgbox "Shame" 12 25
fi

# clear the last dialog box and exit the program
sleep 2
dialog --clear
exit 0
