scope: scope.cpp
	g++ -o $@ $@.cpp

dowhile: dowhile.cpp
	g++ -o $@ $@.cpp

for: for.cpp
	g++ -o $@ $@.cpp
	
if: if.cpp
	g++ -o $@ $@.cpp

switch: switch.cpp
	g++ -o $@ $@.cpp
	
switch_geek: switch_geek.cpp
	g++ -o $@ $@.cpp -std=c++11

while: while.cpp
	g++ -o $@ $@.cpp

goto: goto.cpp
	g++ -o $@ $@.cpp

exception: exception.cpp
	g++ -o $@ $@.cpp -std=c++11

divide: divide.cpp
	g++ -o $@ $@.cpp
